/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package foodcityresidencecomplex.Views;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sanuri Isara
 */
public class BoaderRegistration extends javax.swing.JFrame {
    private Object MosaicUI;

    /**
     * Creates new form BoaderRegistration
     */
    public BoaderRegistration() {
        initComponents();
        autogenrateId();
    }
    
    
    public void autogenrateId() {
        
        try {
             Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/foodcity","root","");
             Statement stmt=con.createStatement();    
             ResultSet rs=stmt.executeQuery("SELECT MAX(BoaderID) FROM boader");
            while ( rs.next() ){
            int maxID = rs.getInt(1);
            maxID++;
            txtbid.setText(maxID+"");
    }

            
        } catch (Exception e) {
            e.printStackTrace();
        }
    
    }
    public void clearTxt(){
    txtfname.setText("");
    txtlname.setText("");
    txtAdress.setText("");
    txtHome.setText("Home");
    txtMobil.setText("Mobile");
    txtnic.setText("");
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtbid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtfname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtlname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtnic = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAdress = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        txtMobil = new javax.swing.JTextField();
        txtHome = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableDetail = new javax.swing.JTable();
        btnaddtoRoom = new javax.swing.JButton();
        btnadd = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnsearch = new javax.swing.JButton();
        btnhome = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblImage = new javax.swing.JLabel();
        btnImage = new java.awt.Button();
        jPanel3 = new javax.swing.JPanel();
        btndelete = new javax.swing.JButton();
        btnLoadAll = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tekton Pro", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Boader Registration");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 560, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foodcityresidencecomplex/Views/src/System-Home-icon2.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 125));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Boader ID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 153, 163, 27));

        txtbid.setEditable(false);
        getContentPane().add(txtbid, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 153, 233, 27));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("First Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 198, 163, 27));
        getContentPane().add(txtfname, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 198, 233, 27));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Last Name");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 243, 163, 27));
        getContentPane().add(txtlname, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 243, 233, 27));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("NIC");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 288, 163, 27));
        getContentPane().add(txtnic, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 288, 233, 27));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Address");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 333, 163, 27));

        txtAdress.setColumns(20);
        txtAdress.setRows(5);
        jScrollPane1.setViewportView(txtAdress);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 333, 233, 66));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Contact No");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 417, 163, 27));

        txtMobil.setText("Mobile");
        getContentPane().add(txtMobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 417, 233, 27));

        txtHome.setText("Home");
        getContentPane().add(txtHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 455, 233, 27));

        tableDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BoaderID", "FirstName", "LastName", "NIC", "Address", "Contact Mobile", "Contact Home"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableDetail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDetailMouseClicked(evt);
            }
        });
        tableDetail.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tableDetailPropertyChange(evt);
            }
        });
        jScrollPane2.setViewportView(tableDetail);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 488, 640, 160));

        btnaddtoRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foodcityresidencecomplex/Views/src/room.png"))); // NOI18N
        btnaddtoRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddtoRoomActionPerformed(evt);
            }
        });
        getContentPane().add(btnaddtoRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 60, 150, 90));

        btnadd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foodcityresidencecomplex/Views/src/download-database-icon.png"))); // NOI18N
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });
        getContentPane().add(btnadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 290, 80, 80));

        btnupdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foodcityresidencecomplex/Views/src/Icons_respaldo.png"))); // NOI18N
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 420, 80, 80));

        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foodcityresidencecomplex/Views/src/nTBXErGEc.jpeg"))); // NOI18N
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 293, 80, -1));

        btnsearch.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sanuri Isara\\Documents\\NetBeansProjects\\FoodCityResidenceComplex\\Resourses\\ICON\\search(1).png")); // NOI18N
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 165, 80, 80));

        btnhome.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sanuri Isara\\Documents\\NetBeansProjects\\FoodCityResidenceComplex\\Resourses\\ICON\\System-Home-icon - Copy - Copy.png")); // NOI18N
        btnhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhomeActionPerformed(evt);
            }
        });
        getContentPane().add(btnhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 420, 80, 80));

        btnexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foodcityresidencecomplex/Views/src/exit-icon-2.png"))); // NOI18N
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });
        getContentPane().add(btnexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 540, 80, 80));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 34, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImage, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, 130, 150));

        btnImage.setLabel("Photo");
        btnImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImageActionPerformed(evt);
            }
        });
        getContentPane().add(btnImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, 130, 30));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 340, 130, 140));

        btndelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foodcityresidencecomplex/Views/src/remove-from-database-icon.png"))); // NOI18N
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 540, 80, 80));

        btnLoadAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foodcityresidencecomplex/Views/src/user-database-icon-search.png"))); // NOI18N
        btnLoadAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadAllActionPerformed(evt);
            }
        });
        getContentPane().add(btnLoadAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 160, 80, 80));

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sanuri Isara\\Documents\\NetBeansProjects\\FoodCityResidenceComplex\\Resourses\\ICON\\Light-Pink-Background.jpg")); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnaddtoRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddtoRoomActionPerformed
        this.dispose();
        new AddToRoom().setVisible(true);
        
    }//GEN-LAST:event_btnaddtoRoomActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
      
        try {
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/foodcity","root","");
            Statement stmt=con.createStatement(); 
            int x=Integer.parseInt(txtMobil.getText());
            int y=Integer.parseInt(txtHome.getText());
            DefaultTableModel dt=(DefaultTableModel) tableDetail.getModel();
            stmt.executeUpdate("INSERT INTO boader(BoaderID,FirstName,LastName,NIC,Address,ContactMobile,ContactHome,Image,QR)VALUES('"+txtbid.getText()+"','"+txtfname.getText()+"','"+txtlname.getText()+"','"+txtnic.getText()+"','"+txtAdress.getText()+"','"+x+"','"+y+"','"+"gghjjj"+"','"+"dfghjk"+"')");
            Vector v=new Vector();
            v.add(txtbid.getText());
            v.add(txtfname.getText());
             v.add(txtlname.getText());
            v.add(txtnic.getText());
            v.add(txtAdress.getText());
            v.add(txtMobil.getText());
             v.add(txtHome.getText());
            dt.addRow(v);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnaddActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
      
        try {
             Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/foodcity","root","");
            Statement stmt=con.createStatement();
            
           stmt.executeUpdate("UPDATE boader SET FirstName='"+txtfname.getText()+"',LastName='"+txtlname.getText()+"',NIC='"+txtnic.getText()+"',Address='"+txtAdress.getText()+"',ContactMobile='"+txtMobil.getText()+"',ContactHome='"+txtHome.getText()+"',Image='"+"ffgghg"+"',QR='"+"fgth"+"'WHERE boaderID='"+txtbid.getText()+"'");
        } catch (Exception e) {
            e.printStackTrace();
                   
        }
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        try {
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/foodcity","root","");
            Statement s=con.createStatement();
            DefaultTableModel dtm=(DefaultTableModel) tableDetail.getModel();
           
            dtm.setRowCount(0);
            autogenrateId();
            clearTxt();
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
      new SearchBoaderDetails().setVisible(true);
      this.dispose();
    }//GEN-LAST:event_btnsearchActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
          try {
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/foodcity","root","");
            Statement s=con.createStatement();
            DefaultTableModel dtm=(DefaultTableModel) tableDetail.getModel();
            int srw=tableDetail.getSelectedRow();
            String bid=dtm.getValueAt(srw, 0).toString();
            s.executeUpdate("DELETE  FROM boader WHERE boaderID='"+bid+"'");
            dtm.removeRow(srw);
            autogenrateId();
            clearTxt();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed

        this.dispose();
    }//GEN-LAST:event_btnexitActionPerformed

    private void btnhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomeActionPerformed
      new Home().setVisible(true);
    }//GEN-LAST:event_btnhomeActionPerformed

    private void tableDetailPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tableDetailPropertyChange
          try {
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/foodcity","root","");
            Statement s=con.createStatement();
            DefaultTableModel dtm=(DefaultTableModel) tableDetail.getModel();
            int srw=tableDetail.getSelectedRow();
          
         
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_tableDetailPropertyChange

    private void btnLoadAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadAllActionPerformed
        try {
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/foodcity","root","");
            Statement stmt=con.createStatement(); 
            DefaultTableModel dtm=(DefaultTableModel) tableDetail.getModel();
           
           ResultSet rs=stmt.executeQuery("SELECT BoaderID,FirstName,LastName,NIC,Address,ContactMobile,ContactHome FROM boader"); 
                          while (rs.next()) {
                             
                Vector v=new Vector();
               
                v.add(rs.getString(1));
                v.add(rs.getString(2));
                v.add(rs.getString(3));
                v.add(rs.getString(4));
                v.add(rs.getString(5));
                v.add(rs.getString(6));
                v.add(rs.getString(6));
               
                dtm.addRow(v);
                          }
        } catch (Exception e) {
        }
             
       
        
    }//GEN-LAST:event_btnLoadAllActionPerformed

    private void tableDetailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDetailMouseClicked
       
        try {
            DefaultTableModel dtm=(DefaultTableModel) tableDetail.getModel();
            int srw=tableDetail.getSelectedRow();
            txtbid.setText((String) dtm.getValueAt(srw, 0));
            txtfname.setText(dtm.getValueAt(srw, 1).toString());
            txtlname.setText(dtm.getValueAt(srw, 2).toString());
            txtnic.setText(dtm.getValueAt(srw, 3).toString());
            txtAdress.setText(dtm.getValueAt(srw, 4).toString());
            txtMobil.setText(dtm.getValueAt(srw, 5).toString());
            txtHome.setText(dtm.getValueAt(srw, 6).toString());

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_tableDetailMouseClicked

    private void btnImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImageActionPerformed
 /*       // TODO add your handling code here:
        JFileChooser filechooser= new JFileChooser();
    filechooser.setDialogTitle("Choose Your File");
    filechooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
    //below codes for select  the file 
    int returnval=filechooser.showOpenDialog(this);
    if(returnval==JFileChooser.APPROVE_OPTION)
    {
        File file = filechooser.getSelectedFile();
        BufferedImage bi;
        try
        {   //display the image in jlabel
            bi=ImageIO.read(file);

            .setIcon(new ImageIcon(bi));
        }
        catch(IOException e)
        {

        }
        this.pack();
    }}
        */
         
    }//GEN-LAST:event_btnImageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BoaderRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BoaderRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BoaderRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BoaderRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BoaderRegistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private java.awt.Button btnImage;
    private javax.swing.JButton btnLoadAll;
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnaddtoRoom;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnhome;
    private javax.swing.JButton btnsearch;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblImage;
    private javax.swing.JTable tableDetail;
    private javax.swing.JTextArea txtAdress;
    private javax.swing.JTextField txtHome;
    private javax.swing.JTextField txtMobil;
    private javax.swing.JTextField txtbid;
    private javax.swing.JTextField txtfname;
    private javax.swing.JTextField txtlname;
    private javax.swing.JTextField txtnic;
    // End of variables declaration//GEN-END:variables
}
