/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package foodcityresidencecomplex.Views;

import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;

/**
 *
 * @author glsik1
 */
public class Login extends javax.swing.JFrame {

 
    
    public Login() {
        initComponents();
        lblLogin.setText("");
    }
    //Connection
    
      public void connection(){
      
          try {
           Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/foodcity","root","");
           Statement stmt=con.createStatement();   
          } catch (Exception e) {
          }
      
      }
      //Run progress bar
      
      public void starProgress(){
          for (int i = 0; i < 101; i++) {
              jProgressBar2.setValue(i);
              
              if (i==100) {
                  lblLogin.setText("LOGIN SUCESSESFUL");
                  try {
                   Thread.sleep(1000);   
                      
                      new Thread(new Runnable() {

                          @Override
                          public void run() {
                          }
                      }).start();
                  } catch (Exception e) {
                  }
                
                 
    
              }
              
          }
      
      }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtpass = new javax.swing.JPasswordField();
        txtuser = new javax.swing.JTextField();
        btnlogin = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jProgressBar2 = new javax.swing.JProgressBar();
        lblLogin = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tekton Pro Cond", 0, 48)); // NOI18N
        jLabel2.setText("Food City Residence Complex");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 490, 100));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 190, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("User Name");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 140, 30));
        getContentPane().add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 280, 30));
        getContentPane().add(txtuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 280, 30));

        btnlogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foodcityresidencecomplex/Views/src/user_login_man-512 - Copy.png"))); // NOI18N
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });
        getContentPane().add(btnlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 80, 80));

        btnCancel.setBackground(new java.awt.Color(255, 255, 255));
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foodcityresidencecomplex/Views/src/download 10 copy.jpg"))); // NOI18N
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, 80, 80));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foodcityresidencecomplex/Views/src/System-Home-icon2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jProgressBar2.setOpaque(true);
        jProgressBar2.setStringPainted(true);
        getContentPane().add(jProgressBar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 620, 20));

        lblLogin.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lblLogin.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(lblLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 220, 20));

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sanuri Isara\\Documents\\NetBeansProjects\\FoodCityResidenceComplex\\Resourses\\ICON\\Light-Pink-Background.jpg")); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
        try {
             String username=txtuser.getText();
             String pass=new String(txtpass.getPassword());
             System.out.println(pass+""+username);
             Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/foodcity","root","");
             Statement stmt=con.createStatement();    
             ResultSet rs=stmt.executeQuery("SELECT * FROM user where userName='"+username+"' AND password='"+pass+"'");
            if(rs.next()) {
                 System.out.println("Correct");
                 starProgress();
                // this.dispose(); 
                // new Home().setVisible(true);
                 
                
            }else{
                lblLogin.setText("LOGIN FAIL");
                jProgressBar2.setValue(0);
            }
             
            
            
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_btnloginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {   
                    Thread.sleep(5000);
                } catch (InterruptedException ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                }
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnlogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables

    private void Home() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
