/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package foodcityresidencecomplex.Views;

/**
 *
 * @author Sanuri Isara
 */
public class Payment extends javax.swing.JFrame {

    /**
     * Creates new form Payment
     */
    public Payment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        txtbid = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmbPaymentType = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnadd = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnsearch = new javax.swing.JButton();
        btnhome = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();
        txtfname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtlname = new javax.swing.JTextField();
        txtpaymentAmount = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtnic = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Boader ID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 153, 163, 27));

        txtbid.setEditable(false);
        getContentPane().add(txtbid, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 230, 27));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("First Name");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 198, 163, 27));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Payment Type");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 163, 27));

        cmbPaymentType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cmbPaymentType, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 230, 29));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Payment Amount");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 163, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foodcityresidencecomplex/Views/src/System-Home-icon2.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 125));

        jLabel1.setFont(new java.awt.Font("Tekton Pro", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Payments Details");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 460, 80));

        btnadd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foodcityresidencecomplex/Views/src/download-database-icon.png"))); // NOI18N
        getContentPane().add(btnadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 80, 80));

        btnupdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foodcityresidencecomplex/Views/src/Icons_respaldo.png"))); // NOI18N
        getContentPane().add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 80, 80));

        btndelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foodcityresidencecomplex/Views/src/remove-from-database-icon.png"))); // NOI18N
        getContentPane().add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, 80, 80));

        btnsearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foodcityresidencecomplex/Views/src/user-database-icon-search.png"))); // NOI18N
        getContentPane().add(btnsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 400, 80, 80));

        btnhome.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sanuri Isara\\Documents\\NetBeansProjects\\FoodCityResidenceComplex\\Resourses\\ICON\\System-Home-icon - Copy - Copy.png")); // NOI18N
        getContentPane().add(btnhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 400, 80, 80));

        btnexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foodcityresidencecomplex/Views/src/exit-icon-2.png"))); // NOI18N
        getContentPane().add(btnexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 400, 80, 80));
        getContentPane().add(txtfname, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 198, 233, 27));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Last Name");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 243, 163, 27));
        getContentPane().add(txtlname, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 230, 27));
        getContentPane().add(txtpaymentAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 243, 233, 27));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Add New Payment Type");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, 150, 27));
        getContentPane().add(txtnic, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 340, 110, 27));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foodcityresidencecomplex/Views/src/698913-icon-81-document-add-1282.png"))); // NOI18N
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 340, 30, 30));

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sanuri Isara\\Documents\\NetBeansProjects\\FoodCityResidenceComplex\\Resourses\\ICON\\Light-Pink-Background.jpg")); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnhome;
    private javax.swing.JButton btnsearch;
    private javax.swing.JButton btnupdate;
    private javax.swing.JComboBox cmbPaymentType;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtbid;
    private javax.swing.JTextField txtfname;
    private javax.swing.JTextField txtlname;
    private javax.swing.JTextField txtnic;
    private javax.swing.JTextField txtpaymentAmount;
    // End of variables declaration//GEN-END:variables
}
